<?php
/**
 * Diglin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 *
 * @category    Diglin
 * @package     Diglin_UIOptimization
 * @copyright   Copyright (c) 2011-2012 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/*@var $this Rissip_UIOptimization_Block_Optimize_Head */
$canonicalUrl = htmlspecialchars($this->getCanonicalUrl());
if(Mage::getStoreConfigFlag('uioptimization/seo/enabled') && $canonicalUrl) :
?>
<link rel="canonical" href="<?php echo $canonicalUrl; ?>" />
<?php endif; ?>